Rogue-Ape-Studios-XR/Secrets-of-Ignacios

- Manifesto.md
Manifesto has been updated. Roles, DoD have been added, communication, daily tasks have been updated.
`Manifesto.md` : Was updated / renamed. Roles, DoD have been added, communication, daily tasks have been updated.
Read to see if it is correct.
> 📝Update manifesto

- Assets/Prefabs/PlayerRig/MR Interaction Setup.prefab
- Assets/Scripts/Player.meta
- Assets/Scripts/Player/Movement.meta
- Assets/Scripts/Player/Movement/AlternateMovement.cs
- Assets/Scripts/Player/Movement/AlternateMovement.cs.meta
Adds the alternate movement to the player rig prefab. Player can now move using shaka hand sign (fist was too inconsistent), a little ball (can be changed later) indicates the direction, like a joystick.
`Assets/Scripts/Player/Movement/AlternateMovement.cs` : Was created. This is the alternate movement script.
`Assets/Prefabs/PlayerRig/MR Interaction Setup.prefab` : Was updated / renamed. Has the new script and required objects with set values. Play ready.
1. Drag the prefab into a scene
2. Make shaka hand sign 🤙
3. Move around
Closes #12
> ✨ Alternate movement

- Assets/Packs/PolygonDungeon/Materials/Alternatives/Dungeon_Material_01_B.mat
- Assets/Scenes/MainLevel.unity
- Assets/Scenes/MainLevel.unity.meta
Created the central room based on the gray boxing
Look discord [gif-img-art](https://cdn.discordapp.com/attachments/1281574362373423185/1286992105729949747/central_room.gif?ex=66f1e68d&is=66f0950d&hm=4558765f547422ca1aabc034c15d891e44d7a94d1a8c9a74873289685859a561&) for gif.
`Assets/Scenes/MainLevel.unity` : Was created.
1. open the scene
2. play / look around
Closes #11
> 🎨central room

- Assets/Scenes/Gray Boxing/Gray boxing.unity
Created gray boxing based on miro board design of the first rooms (teleport, fire, fake wall)
`Assets/Scenes/Gray Boxing/Gray boxing.unity` : Was updated.
Closes #16
> 🎨gray boxing room 1

- Assets/Scenes/Gray Boxing/Gray boxing.unity
Created gray boxing based on miro board design of room 2 (water)
`Assets/Scenes/Gray Boxing/Gray boxing.unity` : Was updated.
Closes #18
> 🎨Gray boxing room 2

- Assets/Scenes/Gray Boxing/Gray boxing.unity
Created gray boxing based on miro board design of room 3 (air)
`Assets/Scenes/Gray Boxing/Gray boxing.unity` : Was updated
Closes #19
> 🎨gray boxing room 3

- Assets/Scenes/Gray Boxing/Gray boxing.unity
Created gray boxing based on miro board design of room 4
`Assets/Scenes/Gray Boxing/Gray boxing.unity` : Was updated
Closes #20
> 🎨Created room 4

- Assets/Settings/Project Configuration/Standalone Balanced Preset.asset
- Assets/Settings/Project Configuration/Standalone Performant Preset.asset
- Assets/Settings/Project Configuration/UniversalRenderPipelineGlobalSettings.asset
- Assets/VFX.meta
- Assets/VFX/DebugSpellHold.vfx
- Assets/VFX/DebugSpellHold.vfx.meta
- Assets/VFX/DebugSpellImpact.vfx
- Assets/VFX/DebugSpellImpact.vfx.meta
- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/EditorBuildSettings.asset
- ProjectSettings/ProjectSettings.asset
- ProjectSettings/VFXManager.asset
📦️ Added the VFX Graph package to the project
🍱 Added 2 VFX for testing spells
1. Drag the new VFX graphs into the scene.
2. 1 should create a constant swirl and the other should look like a small implosion. The implosion can be replayed if the respective object is selected.
Closes #42
> 📦️🍱 Added the VFX Graph package to the project and added 2 VFX for testing spells

- Assets/Scenes/Gray Boxing/Gray boxing.unity
- Assets/Settings/Project Configuration/Standalone Balanced Preset.asset
- Assets/Settings/Project Configuration/Standalone Performant Preset.asset
- Assets/Settings/Project Configuration/UniversalRenderPipelineGlobalSettings.asset
- Assets/VFX.meta
- Assets/VFX/DebugSpellHold.vfx
- Assets/VFX/DebugSpellHold.vfx.meta
- Assets/VFX/DebugSpellImpact.vfx
- Assets/VFX/DebugSpellImpact.vfx.meta
- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/EditorBuildSettings.asset
- ProjectSettings/ProjectSettings.asset
- ProjectSettings/VFXManager.asset
Update branch with dev, so I can have the vfx package.
> 🎨fire-puzzle-prototype

- Assets/Scenes/MainLevel.unity
Created The starting, teleport and fire rooms
https://cdn.discordapp.com/attachments/1281574362373423185/1290264212513357825/Room_1.gif?ex=66fbd3b0&is=66fa8230&hm=ce919b946b4809f9d41ba88ee49d7965f053c7e3653d2ab19cee6e077b454830&
`Assets/Scenes/MainLevel.unity` : Was updated
Closes #29
> 🎨Created starting, teleport and fire rooms

- .idea/.idea.Secrets-of-Ignacios/.idea/.gitignore
- .idea/.idea.Secrets-of-Ignacios/.idea/encodings.xml
- .idea/.idea.Secrets-of-Ignacios/.idea/indexLayout.xml
- .idea/.idea.Secrets-of-Ignacios/.idea/misc.xml
- .idea/.idea.Secrets-of-Ignacios/.idea/vcs.xml
- Assets/Scripts/Teleport.meta
- Assets/Scripts/Teleport/HandleHandTeleport.cs
- Assets/Scripts/Teleport/HandleHandTeleport.cs.meta
- Assets/XR/Settings/OpenXRPackageSettings.asset
- ProjectSettings/TagManager.asset
Added the option to teleport using hand gestures. Can trigger events in the script to either disable, enable and trigger the teleport.
Player teleport was added, as well as the layer "Teleportable surface". This layer is reserved for anything the player can teleport on.
Prefab has minor changes, but this is not pushed and will be need to be implemented the same when testing.
MRI prefab not changed, but the changes necessary to make teleport work will be detailed in Testing.
-HandleHandTeleport.cs 
-Teleportable surface layer
1: Add a plane into a scene, and give it the "Teleportation Area" script. Select Teleport as Interaction Layer Mask and add the mesh collider to the "colliders"
2: Give the plane the layer "Teleportable …
> ✨Hand teleportation feature

- Assets/Prefabs/Puzzles.meta
- Assets/Prefabs/Puzzles/FireRoom.meta
- Assets/Prefabs/Puzzles/FireRoom/GloomStalk.prefab
- Assets/Prefabs/Puzzles/FireRoom/GloomStalk.prefab.meta
- Assets/Scenes/Gray Boxing/Puzzle test gray boxing.unity
- Assets/Scripts/Interactables/DestructiveBurning.cs
- Assets/Scripts/Interactables/PersistentFire.cs
Changed some code to adhere to the code convention and remove commented code, create a prefab for an interactable, added the prefab to the grayboxing scene. Everything worked like it did before.
`Assets/Prefabs/Puzzles/FireRoom/GloomStalk.prefab` : Was created. Works with the updated script for interactable.
`Assets/Scenes/Gray Boxing/Puzzle test gray boxing.unity` : Was updated / renamed. Added prefab to the scene.
`Assets/Scripts/Interactables/DestructiveBurning.cs` : Was updated / renamed. Updated code for better performance and to adhere to the code convention.
`Assets/Scripts/Interactables/PersistentFire.cs` : Was updated / renamed. Commented code has been removed.
1. Run `Assets/Scenes/Gray Boxing/Puzzle test gray …
> ♻️ Fire puzzle

- Assets/Prefabs/PlayerRig/MR Interaction Setup.prefab
The MR Interaction prefab has been modified to have the teleport feature attached to it.
`Assets/Prefabs/PlayerRig/MR Interaction Setup.prefab` : Was updated to incorporate the teleportation feature.
1. Drag the MR Interaction prefab into a scene
2: Add a plane into a scene, and give it the "Teleportation Area" script. Select Teleport as Interaction Layer Mask and add the mesh collider to the "colliders"
3: Give the plane the layer "Teleportable surface"
4.  Under Gesture Detection, choose a gesture under Right Hand and make an event on "performed" to activate Activate Teleport, and on "ended" the Trigger Teleport and Deactivate Teleport. (Drag in the Right Hand component where the HandleHandTeleport script is attached).
> ✨ Integrated the teleport feature into the existing MR prefab

- Assets/Scenes/MainLevel.unity
[Created water room](https://cdn.discordapp.com/attachments/1281574362373423185/1290982518664724521/Water_room.gif?ex=66fe70a9&is=66fd1f29&hm=b09d590968fec8d340fc546070ecf0e19c270912d004f9b1777264f6952b43af&)
`Assets/Scenes/MainLevel.unity` : Was updated
Closes #31
> 🎨Created water room

- Assets/Scripts/Player/SpellMagicCircle/MagicCirclePlayerFeedback.cs
Fixed a script that did not have the correct name due to a merge
`MagicCirclePlayerFeedback.cs` : Was updated to not give a compile error.
1. Open Unity. It should not give any compile errors.
> 🚑️ Changed script to use the correct gestures to fix a compile error

- Assets/Scripts/Interactables/Water/Fillable.cs
- Assets/Scripts/Interactables/Water/Washable.cs
- Assets/Scripts/Interactables/Water/WaterInteractable.cs
Added functionality for the water interactable.
`Assets/Scripts/Interactables/Water/Fillable.cs` : Was updated.
`Assets/Scripts/Interactables/Water/Washable.cs` : Was updated.
`Assets/Scripts/Interactables/Water/WaterInteractable.cs` : Was updated.
> ✨ interactables system water

- Assets/Scripts/Interactables/Fire/DestructiveBurning.cs
- Assets/Scripts/Interactables/Fire/FireInteractable.cs
- Assets/Scripts/Interactables/Fire/PersistentFire.cs
Added douse functionality to the fire interactable
`Assets/Scripts/Interactables/Fire/DestructiveBurning.cs` : Was updated.
`Assets/Scripts/Interactables/Fire/FireInteractable.cs` : Was updated.
`Assets/Scripts/Interactables/Fire/PersistentFire.cs` : Was updated.
`File` : Was removed. You can add the reason here.
Closes #67
> ✨ interactables system fire

- Assets/Prefabs/Grimiore.meta
- Assets/Prefabs/Grimiore/Bookholder.prefab
- Assets/Prefabs/Grimiore/Bookholder.prefab.meta
- Assets/Prefabs/Grimiore/Bracelet Holder.prefab
- Assets/Prefabs/Grimiore/Bracelet Holder.prefab.meta
- Assets/Prefabs/Grimiore/Grimiore.prefab
- Assets/Prefabs/Grimiore/Grimiore.prefab.meta
- Assets/Prefabs/Grimiore/HeadGazeInteractor.prefab
- Assets/Prefabs/Grimiore/HeadGazeInteractor.prefab.meta
- Assets/Prefabs/PlayerRig/MR Interaction Setup.prefab
- Assets/Samples/XR Interaction Toolkit/3.0.5/Hands Interaction Demo/Materials/Unity_Hand_Medium.mat
- Assets/Scripts/UI.meta
- Assets/Scripts/UI/GrimoireUIController.cs
- Assets/Scripts/UI/GrimoireUIController.cs.meta
- Assets/XRI/Settings/Resources/InteractionLayerSettings.asset
Added the ability for the player to summon the grimiore and made appropriate prefabs for further development
`Prefabs/Grimiore` : Was created. A fully functional prefab that has the book and bracelet holder so that the player can 
`Prefabs/BookHolder` : Was created. A prefab that holds the grimiore, which will later be used for the player to store learned spells and look back when in need.
`Prefabs/Bracelet Holder` : Was created. A prefab that holds a button which can appear on the back of the player's hand.
`Prefabs/HeadGazeInteractor` : Was created. This object is placed on the player to track if the player is looking at certain objects
`Scripts/Bracelet Holder` : Was created. You can add the purpose here.
`MR Interaction setup` : Was updated with the grimiore and headgazeinteractor. …
> ✨grimiore summoning

- Assets/Scenes/MainLevel.unity
[Created earth room](https://cdn.discordapp.com/attachments/1281574362373423185/1291725105600139284/Room_4.gif?ex=67012440&is=66ffd2c0&hm=02cafea96fc563a33c12b15db701de5bcb41b7e0a24e73a5051e59fcfbf26f7f&)
`Assets/Scenes/MainLevel.unity` : Was updated
Closes #33
> 🎨Created earth room

- .gitignore
- Assets/Samples/XR Hands/1.4.1/Gestures/Examples/Hand Poses/Finger Gun.asset
- Assets/Samples/XR Hands/1.4.1/Gestures/Examples/Hand Poses/Finger Gun.asset.meta
- Assets/Samples/XR Hands/1.4.1/Gestures/Examples/Hand Poses/Palm Forward.asset
- Assets/Samples/XR Hands/1.4.1/Gestures/Examples/Hand Poses/Palm Forward.asset.meta
- Assets/Samples/XR Hands/1.4.1/Gestures/Examples/Hand Poses/Palm Sideways.asset
- Assets/Samples/XR Hands/1.4.1/Gestures/Examples/Hand Poses/Palm Sideways.asset.meta
- Assets/Samples/XR Hands/1.4.1/Gestures/Examples/Hand Shapes/Finger Gun Hand Shape.asset
- Assets/Samples/XR Hands/1.4.1/Gestures/Examples/Hand Shapes/Finger Gun Hand Shape.asset.meta
- Assets/Samples/XR Hands/1.4.1/Gestures/Examples/Hand Shapes/Point Hand Shape.asset
- Assets/Samples/XR Hands/1.4.1/Gestures/HandGestures.unity
Added 3 new gestures, finger gun, palm sideways and forward. The sample level of hand gesture has been updated, so these gestures can be immediatly tested. Added xr plugin to gitignore as well.
`Assets/Samples/XR Hands/1.4.1/Gestures/Examples/Hand Poses/Finger Gun.asset` : Was created. 
`Assets/Samples/XR Hands/1.4.1/Gestures/Examples/Hand Poses/Palm Forward.asset` : Was created. 
`Assets/Samples/XR Hands/1.4.1/Gestures/Examples/Hand Poses/Palm Sideways.asset` : Was created.
`Assets/Samples/XR Hands/1.4.1/Gestures/Examples/Hand Shapes/Finger Gun Hand Shape.asset` : Was created. 
`Assets/Samples/XR Hands/1.4.1/Gestures/Examples/Hand Shapes/Point Hand Shape.asset` : Was updated / renamed. Can now better distinct between finger gun and point.
`Assets/Samples/XR …
> ✨ New hand gestures

- Assets/Animations.meta
- Assets/Animations/DoorOpen.anim
- Assets/Animations/DoorOpen.anim.meta
- Assets/Animations/SingleDoor.controller
- Assets/Animations/SingleDoor.controller.meta
Added animation for a single door that opens.
`Assets/Animations/DoorOpen.anim` : Was created.
`Assets/Animations/SingleDoor.controller` : Was created.
Closes #83
> 💫 fire room animations

- Assets/Animations/DoorOpen.anim
- Assets/Animations/SingleDoor.controller
- Assets/Scripts/Puzzle/FireRoom/TorchPuzzleCheck.cs
Updates door animation logic so it actually works.
`Assets/Animations/DoorOpen.anim` : Was updated / renamed. Update the animation.
`Assets/Animations/SingleDoor.controller` : Was updated / renamed. Updated the controller so it has a trigger and a functioning flow.
`Assets/Scripts/Puzzle/FireRoom/TorchPuzzleCheck.cs` : Was updated / renamed. Works with the new controller now.
1. Open puzzle test grayboxing scene 
2. Go to the door, add an animator to the door.
3. Drag animator into torch puzzle check reference
4. In the animator put single door animator as reference
> 💫 Door open anim

- Assets/Scenes/Gray Boxing/Puzzle test gray boxing.unity
Updated puzzle test gray box area, now has big door, tp planes and added some folders for order.
`Assets/Scenes/Gray Boxing/Puzzle test gray boxing.unity` : Was updated / renamed. 
1. Play in level
> 🎨 Puzzle test graybox

- Assets/VFX/SpellCharge.meta
- Assets/VFX/SpellCharge/SpellCharge.vfx
- Assets/VFX/SpellCharge/SpellCharge.vfx.meta
Added a single VFX for the charge up spell aiming type
`Assets/VFX/SpellCharge/SpellCharge.vfx` : Was created.  Visual feedback for aiming through time delay
1. Place the new VFX in the scene
2. Click on it and press Play
3. Try changing anim speed
> 🍱 Added spell charge VFX

- Assets/Materials/BlockView.meta
- Assets/Materials/BlockView/BlackBox.mat
- Assets/Materials/BlockView/BlackBox.mat.meta
- Assets/Prefabs/PlayerRig/HeadDetectionBlockView.prefab
- Assets/Prefabs/PlayerRig/HeadDetectionBlockView.prefab.meta
- Assets/Prefabs/PlayerRig/HeadDetectionPushBack.prefab
- Assets/Prefabs/PlayerRig/HeadDetectionPushBack.prefab.meta
- Assets/Scripts/HeadDetection.meta
- Assets/Scripts/HeadDetection/BlockView.cs
- Assets/Scripts/HeadDetection/BlockView.cs.meta
- Assets/Scripts/HeadDetection/HeadCollisionDetector.cs
- Assets/Scripts/HeadDetection/HeadCollisionDetector.cs.meta
- Assets/Scripts/HeadDetection/HeadPushBack.cs
- Assets/Scripts/HeadDetection/HeadPushBack.cs.meta
Added anti wall hacks features,
1. One that blacks out you screen when in the wall.
2. One that pushes you back when you try to put your head in the wall.
`Assets/Materials/BlockView/BlackBox.mat` : Was created.
` Assets/Prefabs/PlayerRig/HeadDetectionBlockView.prefab` : Was created.
` Assets/Prefabs/PlayerRig/HeadDetectionPushBack.prefab` : Was created.
` Assets/Scripts/HeadDetection/BlockView.cs` : Was created.
` Assets/Scripts/HeadDetection/HeadCollisionDetector.cs` : Was created.
`Assets/Scripts/HeadDetection/HeadPushBack.cs ` : Was created.
black out
1. open the test scene
2. add the black out prefab to the main cam of the rig
push back
1. open the test scene
2. add the push back prefab to the main cam of the rig
3. Ref …
> ✨Prevent head in wall

- Assets/Scripts/Interactables/Wind/Spinnable.cs
- Assets/Scripts/Interactables/Wind/Spinnable.cs.meta
- Assets/Scripts/Interactables/Wind/WindInteractable.cs
Created a new wind interactable, since turnable was not sufficient for the fan puzzle, this one has acceleration of spin and deceleration, it stays spinning as long as it has speed. Max speed, deceleration, speed gained on blown and axis are all editable in the editor.
`Assets/Scripts/Interactables/Wind/Spinnable.cs` : Was created. New interactable script.
`Assets/Scripts/Interactables/Wind/WindInteractable.cs` : Was updated / renamed. Changed onBlown to OnBlown.
1. Put `Spinnable` and `SpellReceiver` script on any object
2. Drag in the transform of the object you want to spin and the `SpellReceiver` in its slot
3. Put a number in the axis you want the object to rotate in (it has a tooltip you can read)
4. Play and press the …
> ✨ Interactable spinnable

- Assets/Animations/Temporary.meta
- Assets/Animations/Temporary/Door.controller
- Assets/Animations/Temporary/Door.controller.meta
- Assets/Animations/Temporary/DoorClose.anim
- Assets/Animations/Temporary/DoorClose.anim.meta
- Assets/Animations/Temporary/DoorOpen.anim
- Assets/Animations/Temporary/DoorOpen.anim.meta
- Assets/Animations/Temporary/Paper.controller
- Assets/Animations/Temporary/Paper.controller.meta
- Assets/Animations/Temporary/PaperBlown.anim
- Assets/Animations/Temporary/PaperBlown.anim.meta
- Assets/Prefabs/Gray Boxing/WindRoom.prefab
- Assets/Prefabs/Gray Boxing/WindRoom.prefab.meta
- Assets/Scripts/Puzzle/General/SequenceChecker.cs
- Assets/Scripts/Puzzle/General/SequenceChecker.cs.meta
- Assets/Scripts/Puzzle/General/SequencePuzzleCollision.cs
- Assets/Scripts/Puzzle/General/SequencePuzzleCollision.cs.meta
- Assets/Scripts/Puzzle/WindRoom.meta
- Assets/Scripts/Puzzle/WindRoom/FanPuzzle.cs
- Assets/Scripts/Puzzle/WindRoom/FanPuzzle.cs.meta
- Assets/Scripts/Puzzle/WindRoom/PipesPuzzle.cs
- Assets/Scripts/Puzzle/WindRoom/PipesPuzzle.cs.meta
- ProjectSettings/TagManager.asset
Added wind puzzle functionalities, these include the puzzle and their consequences only.
`Assets/Animations/Temporary` : Was created. Temp. animations are in this location.
`Assets/Prefabs/Gray Boxing/WindRoom.prefab` : Was created. Room prefab for validating.
`Assets/Scripts/Puzzle/General/SequenceChecker.cs` : Was created. Part of global sequence puzzle system.
`Assets/Scripts/Puzzle/General/SequencePuzzleCollision.cs` : Was created. Part of global sequence puzzle system.
`Assets/Scripts/Puzzle/WindRoom/FanPuzzle.cs` : Was created. Fan puzzle logic.
`Assets/Scripts/Puzzle/WindRoom/PipesPuzzle.cs` : Was created. Animation consequence for vent and pipes puzzle.
1. Place wind room prefab in a scene
2. Activate the spells (Pipes …
> ✨ Wind puzzle prototype

- Assets/Animations/Gate.controller
- Assets/Animations/Gate.controller.meta
- Assets/Animations/GateOpen.anim
- Assets/Animations/GateOpen.anim.meta
- Assets/Animations/SingleDoor.controller
- Assets/Packs/PolygonDungeon/Prefabs/Environments/Walls/SM_Env_Wall_Window_Bars_02.prefab
- Assets/Scripts/Interactables/Water/Fillable.cs
- Assets/Scripts/Interactables/Water/Washable.cs
- Assets/Scripts/Interactables/Water/WaterInteractable.cs
- Assets/Scripts/Puzzle/WaterRoom.meta
- Assets/Scripts/Puzzle/WaterRoom/GatePuzzleCheck.cs
- Assets/Scripts/Puzzle/WaterRoom/GatePuzzleCheck.cs.meta
- Assets/Scripts/Puzzle/WaterRoom/WaterTorchPuzzleCheck.cs
- Assets/Scripts/Puzzle/WaterRoom/WaterTorchPuzzleCheck.cs.meta
Added the scripts for the functionality of the water puzzle prototypes in the water room.
`Assets/Animations/Gate.controller` : Was created. For animation.
`Assets/Animations/GateOpen.anim` : Was created. For animation.
`Assets/Scripts/Puzzle/WaterRoom/GatePuzzleCheck.cs` : Was created. 
`Assets/Scripts/Puzzle/WaterRoom/WaterTorchPuzzleCheck.cs` : Was created. 
`Assets/Animations/SingleDoor.controller` : Was updated. Fixed bug in animation trigger.
`Assets/Packs/PolygonDungeon/Prefabs/Environments/Walls/SM_Env_Wall_Window_Bars_02.prefab` : Was updated. Honestly don't know how/why it changed, haven't touched it.
`Assets/Scripts/Interactables/Water/Fillable.cs` : Was updated. Changed a bool to internal and added an event.
`Assets/Scripts/Interactables/Water/Washable.cs` : Was updated. …
> ✨ water puzzle prototype

- Assets/VFX/Fire/Burning.vfx
- Assets/VFX/Fire/Burning.vfx.meta
Added a VFX for when objects burn (for the Destructive Burning script)
`Burning.vfx` : Was created.
1. Put the VFX in the scene and test by changing some properties
2. Should look like this
> 🎨 Burning vfx

- Assets/Materials/Water/Water.shadergraph
- Assets/Prefabs/SpellProjectiles/Water Projectile.prefab
- Assets/VFX/Water/WaterProjectile.vfx
- Assets/VFX/Water/WaterProjectile.vfx.meta
Updated the water projectile with a new visual effect that is less jarring when casting.
`WaterProjectile.vfx` : Was created. A visual effect that grows over time for the water VFX
`Water.shadergraph` : Was updated. Changed setting to work with VFX graph
`Water Projectile.prefab` : Was updated to include the new VFX
1. Cast the water spell. It should have the projectile grow over time.
2. Should look like this
> 🎨 Water projectile VFX

- Assets/Prefabs/PlayerRig/PlayerRig.prefab
Updated player rig, now has movement and head collision with walls.
`Assets/Prefabs/PlayerRig/PlayerRig.prefab` : Was updated / renamed. 
1. Drag player in scene
2. Move/Teleport
> ✨ Implement new movement

- Assets/Prefabs/SpellProjectiles/Wind Spell.prefab
- Assets/Prefabs/SpellProjectiles/Wind Spell.prefab.meta
- Assets/Scripts/Gestures/ScriptableObjects/TempWindMid.asset
- Assets/Scripts/Gestures/ScriptableObjects/TempWindMid.asset.meta
- Assets/Scripts/Spells/ScriptableObjects/Wind.asset
- Assets/Scripts/Spells/ScriptableObjects/Wind.asset.meta
- Assets/Scripts/Spells/WindSpell.meta
- Assets/Scripts/Spells/WindSpell/WindSpellLogic.cs
- Assets/Scripts/Spells/WindSpell/WindSpellLogic.cs.meta
The wind spell was added with the functionality to push other rigidbodies
`Assets/Prefabs/SpellProjectiles/Wind Spell.prefab` : Was created.
`Assets/Scripts/Gestures/ScriptableObjects/TempWindMid.asset` : Was created. 
`Assets/Scripts/Spells/ScriptableObjects/Wind.asset` : Was created.
`Assets/Scripts/Spells/WindSpell/WindSpellLogic.cs` : Was created.
1. Add the spell properly to the player, Tim knows best how to.
2. Place rigidbodies in front of you
3. Use the spell and enjoy
https://i.imgur.com/z7y9o6Y.gif
Closes #103
> ✨ Wind Spell

- Assets/Prefabs/HeldSpellPrefabs.meta
- Assets/Prefabs/HeldSpellPrefabs/AirHeld.prefab
- Assets/Prefabs/HeldSpellPrefabs/AirHeld.prefab.meta
- Assets/Prefabs/HeldSpellPrefabs/EarthGrow.prefab
- Assets/Prefabs/HeldSpellPrefabs/EarthGrow.prefab.meta
- Assets/Prefabs/HeldSpellPrefabs/EarthShrink.prefab
- Assets/Prefabs/HeldSpellPrefabs/EarthShrink.prefab.meta
- Assets/Prefabs/HeldSpellPrefabs/FireHeld.prefab
- Assets/Prefabs/HeldSpellPrefabs/FireHeld.prefab.meta
- Assets/Prefabs/HeldSpellPrefabs/Hand VFX Manager.prefab
- Assets/Prefabs/HeldSpellPrefabs/Hand VFX Manager.prefab.meta
- Assets/Prefabs/HeldSpellPrefabs/WaterHeld.prefab
- Assets/Prefabs/HeldSpellPrefabs/WaterHeld.prefab.meta
- Assets/Scripts/Gestures/Gesture.cs
- Assets/Scripts/Gestures/ScriptableObjects/Fire.asset
- Assets/Scripts/Gestures/ScriptableObjects/TempWindMid.asset
- Assets/Scripts/Player/SpellMagicCircle/HandVfxManager.cs
- Assets/Scripts/Player/SpellMagicCircle/HandVfxManager.cs.meta
- Assets/Scripts/Player/SpellMagicCircle/MagicCirclePlayerFeedback.cs
- Assets/VFX/Earth/EarthGrow.vfx
- Assets/VFX/Water/WaterHeld.vfx
- Assets/VFX/Water/WaterHeld.vfx.meta
Created a spell visual feedback system that shows the element in the magic circle and then transfers it to your hands upon completing the sequence.
`Hand VFX Manager.prefab` : Was created. A prefab that can be added to the player prefab to create the visual effects for hands and magic circle.
`HandVfxManager.cs` : Was created. A script to make the prefab work. It moves the visual effects to the correct location at the correct moments.
Various hold vfx prefabs were created.
`Gesture.cs` : Was updated to include the visuals in it.
Fire and wind gestures were updated to have said visual effect.
1. Have a scene with the player prefab.
2. Drag the hand vfx manager prefab on the player, directly below XR Origin in the hierarchy
3. Go …
> ✨ Spell element feedback

- Assets/Prefabs/SpellProjectiles/Wind Spell Ranged.prefab
- Assets/Prefabs/SpellProjectiles/Wind Spell Ranged.prefab.meta
- Assets/Scripts/Spells/ScriptableObjects/Wind.asset
- Assets/Scripts/Spells/WindSpell/RangedWindSpellLogic.cs
- Assets/Scripts/Spells/WindSpell/RangedWindSpellLogic.cs.meta
- Assets/Scripts/Spells/WindSpell/WindSpellMovingLogic.cs
- Assets/Scripts/Spells/WindSpell/WindSpellMovingLogic.cs.meta
The wind spell was modified to now be a projectile with a constant push around it.
`Assets/Prefabs/SpellProjectiles/Wind Spell Ranged.prefab` : Was created
`Assets/Scripts/Spells/WindSpell/RangedWindSpellLogic.cs` : Was created
`Assets/Scripts/Spells/WindSpell/WindSpellMovingLogic.cs` : Was created
'Assets/Scripts/Spells/ScriptableObjects/Wind.asset` : Was created
1. Take the player prefab and make sure the gesture and spells are set (so the tempwindmid gesture and wind spell)
2. Drag services into the scene and make sure wind/ air is recognized
3. Find some funny looking rigidbodies
4. Cast the spell
5. Enjoy
Closes #132
> ✨ Wind projectile

- Assets/Prefabs/PlayerRig/PlayerRig.prefab
- Assets/Samples/XR Hands/1.4.1/Gestures/Examples/Hand Poses/Half Circle.asset
- Assets/Samples/XR Hands/1.4.1/Gestures/Examples/Hand Poses/Half Circle.asset.meta
- Assets/Samples/XR Hands/1.4.1/Gestures/Examples/Hand Poses/Half Triangle.asset
- Assets/Samples/XR Hands/1.4.1/Gestures/Examples/Hand Poses/Half Triangle.asset.meta
- Assets/Samples/XR Hands/1.4.1/Gestures/Examples/Hand Poses/Palm Down.asset
- Assets/Samples/XR Hands/1.4.1/Gestures/Examples/Hand Poses/Palm Down.asset.meta
- Assets/Samples/XR Hands/1.4.1/Gestures/Examples/Hand Shapes/Half Circle Shape.asset
- Assets/Samples/XR Hands/1.4.1/Gestures/Examples/Hand Shapes/Half Circle Shape.asset.meta
- Assets/Samples/XR Hands/1.4.1/Gestures/Examples/Hand Shapes/Half Triangle Fingers.asset
- Assets/Samples/XR Hands/1.4.1/Gestures/Examples/Hand Shapes/Half Triangle Fingers.asset.meta
- Assets/Samples/XR Hands/1.4.1/Gestures/HandGestures.unity
- Assets/Scripts/Gestures/HandShape.cs
- Assets/Scripts/Gestures/ScriptableObjects/AirMid.asset
- Assets/Scripts/Gestures/ScriptableObjects/AirMid.asset.meta
- Assets/Scripts/Gestures/ScriptableObjects/Earth.asset
- Assets/Scripts/Gestures/ScriptableObjects/Earth.asset.meta
- Assets/Scripts/Gestures/ScriptableObjects/TouchSpell.asset
- Assets/Scripts/Gestures/ScriptableObjects/TouchSpell.asset.meta
- Assets/Scripts/Spells/ScriptableObjects/Water.asset
- Assets/Scripts/Spells/ScriptableObjects/Wind.asset
*Describe what was changed / fixed here. IE: Updated animation to be centered around the players origin, caught exception, added particle system...*
Added new hand shapes and gestures.
Updated spell sequences and element gestures to match the playtest shown sequences.
Updated player rig with the new gestures to detect.
1. Place updated player rig in your scene.
2. Try out fire, water and wind spells according to the hands image for the playtest
3. Try out gestures for earth according to the hands image for the playtest (these won't produce an earth spell as it is still unimplemented.)
> ✨ New gestures

- Assets/Prefabs/PlayerRig/PlayerRig.prefab
- Assets/Prefabs/SpellProjectiles/EarthGrow.prefab
- Assets/Prefabs/SpellProjectiles/EarthGrow.prefab.meta
- Assets/Prefabs/SpellProjectiles/EarthShrink.prefab
- Assets/Prefabs/SpellProjectiles/EarthShrink.prefab.meta
- Assets/Prefabs/SpellProjectiles/Water Projectile.prefab
- Assets/Scripts/Gestures/ScriptableObjects/Air.asset
- Assets/Scripts/Puzzle/General/Spells/ProjectileSpellLogic.cs
- Assets/Scripts/Services/ObjectPooler.cs
- Assets/Scripts/Spells/Cast.cs
- Assets/Scripts/Spells/CastTypes.cs
- Assets/Scripts/Spells/Earth.meta
- Assets/Scripts/Spells/Earth/Resizable.cs
- Assets/Scripts/Spells/Earth/Resizable.cs.meta
- Assets/Scripts/Spells/Editor.meta
- Assets/Scripts/Spells/Editor/HandConfigEditor.cs
- Assets/Scripts/Spells/Editor/HandConfigEditor.cs.meta
- Assets/Scripts/Spells/Editor/SpellEditor.cs
- Assets/Scripts/Spells/Editor/SpellEditor.cs.meta
- Assets/Scripts/Spells/ScriptableObjects/Earth.asset
- Assets/Scripts/Spells/ScriptableObjects/Earth.asset.meta
- Assets/Scripts/Spells/ScriptableObjects/Fire.asset
- Assets/Scripts/Spells/ScriptableObjects/Water.asset
- Assets/Scripts/Spells/ScriptableObjects/Wind.asset
- Assets/Scripts/Spells/Spell.cs
- Assets/Scripts/Spells/SpellManager.cs
- Assets/Scripts/Spells/WindSpell/RangedWindSpellLogic.cs
- Assets/Scripts/Spells/WindSpell/WindSpellLogic.cs
- Assets/Scripts/Spells/WindSpell/WindSpellMovingLogic.cs
- ProjectSettings/TagManager.asset
Added earth spell this spell needed a lot of refactoring to the current spell system and connected scripts. Also updated player prefab to have the new spell and services, so you just have to drag the player rig into your scene, services is no longer needed separately. 
`Assets/Prefabs/SpellProjectiles/EarthGrow.prefab` : Was created. Grow spell prefab.
`Assets/Prefabs/SpellProjectiles/EarthShrink.prefab` : Was created. Shrink spell prefab.
`Assets/Scripts/Spells/Earth/Resizable.cs` : Was created. Earth spell prefab logic.
`Assets/Scripts/Spells/Editor/HandConfigEditor.cs` : Was created. Editor script.
`Assets/Scripts/Spells/Editor/SpellEditor.cs` : Was created. Editor script.
`Assets/Scripts/Spells/ScriptableObjects/Earth.asset` : Was created. Earth spell SO. …
> ✨ Earth spell

- Assets/Prefabs/Grimiore/Bookholder Moveable.prefab
- Assets/Prefabs/Grimiore/Bookholder Moveable.prefab.meta
- Assets/Prefabs/Grimiore/Bookholder.prefab
- Assets/Prefabs/PlayerRig/MR Interaction Setup With Grimiore.prefab
- Assets/Scripts/UI/GrimoireUIController.cs
Changed the grimoire to be moveable and changed the bracelet button to summon the grimoire
`Assets/Prefabs/Grimoire/Bookholder moveable': A new prefab that has the new changes
`Assets/Prefabs/PlayerRig/MR Interaction Setup With Grimiore.prefab` : Changed to put the book in a different location, so that it no longer attaches to the hand
`Assets/Scripts/UI/GrimoireUIController.cs`: Changed the code so that the bracelet button summons the book to you instead of making it disappear
1. Add prefabs/playerrig/mr interaction with grimoire to a scene
2. Start scene
3. Try out summoning and moving the book
4. Teleport and try it again
Closes #46
> ✨Feature/moveable grimoire

- Assets/Prefabs/SpellProjectiles/EarthGrow.prefab
- Assets/Prefabs/SpellProjectiles/EarthShrink.prefab
`earth prefabs` : Was updated with vfx
1. cast earth spell ofzo
2. profit
> ✨ Added vfx to the earth grow and shrink spell

- Assets/Prefabs/SpellProjectiles/Water Projectile.prefab
- Assets/Prefabs/SpellProjectiles/Wind Spell Ranged.prefab
- Assets/Scripts/Spells/ScriptableObjects/Wind.asset
- Assets/VFX/Water/WaterProjectile.vfx
Changed water spell vfx so no lag and change wind spell so it has the right tag and uses charge.
`Assets/Prefabs/SpellProjectiles/Water Projectile.prefab` : Was updated / renamed. Changed vfx.
`Assets/Prefabs/SpellProjectiles/Wind Spell Ranged.prefab` : Was updated / renamed. Changed tag and radius.
`Assets/Scripts/Spells/ScriptableObjects/Wind.asset` : Was updated / renamed. Changed cast type.
`Assets/VFX/Water/WaterProjectile.vfx` : Was updated / renamed.
1. Use new player rig
2. Cast wind and water spell
> 🐛 Spell projectiles
